# cspell:ignore cmctl gitui krew kubebench kubectx direnv dotenv looztra kompiro kforsthoevel sarg kubeseal stefansedich nlamirault zufardhiyaulhaq sudermanjr
[env]
MISE_PYTHON_COMPILE = false

[tools]
####### Pinned versions
python = '3.13'

######### Latest versions
fzf = "latest"
lsd = "latest"
starship = "latest"
yq = "latest"
zoxide = "latest"

[settings]
experimental = true
http_timeout = "90s"
jobs = 1
yes = true
