# cspell:ignore cmctl gitui krew kubebench kubectx direnv dotenv looztra kompiro kforsthoevel sarg kubeseal stefansedich nlamirault zufardhiyaulhaq sudermanjr openbao kubens
# NOTE: The #### section #### headers below must not be altered or moved as they are used as markers for the install script.

#### Begin Environment ####
[env]
MISE_PYTHON_COMPILE = false
#### End Environment ####

[tools]

# https://github.com/opentofu/opentofu
opentofu = "latest"
# https://github.com/openbao/openbao/releases
openbao = "latest"
#### Begin Kubernetes/Helm ####
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
k9s = "latest"
helm = "latest"
#### End Kubernetes/Helm ####

#### Begin Kubernetes Utilities ####
krew = "latest"
dive = "latest"
kubebench = "latest"
popeye = "latest"
trivy = "latest"
cmctl = "latest"
k3d = "latest"
#### End Kubernetes Utilities ####

#### Begin Go Development ####
golang = 'latest'
goreleaser = 'latest'
#### End Go Development ####

#### Begin .NET Development ####
dotnet = "latest"
#### End .NET Development ####

#### Begin JavaScript/Node.js Development ####
node = "latest"
pnpm = "latest"
yarn = "latest"
deno = "latest"
bun = "latest"
#### End JavaScript/Node.js Development ####

gitui = "latest"
packer = "latest"
tealdeer = "latest"
micro = "latest"
powershell = "latest"

# See: https://mise.jdx.dev/dev-tools/aliases.html for specs on the alias section.
#### Begin Aliases ####
[alias]
kubebench = 'asdf:sarg3nt/asdf-kube-bench'
tealdeer = 'asdf:sarg3nt/asdf-tealdeer'
micro = 'asdf:sarg3nt/asdf-micro'
#### End Aliases ####

#### Begin Settings ####
[settings]
experimental = true
http_timeout = "90s"
yes = true
#### End Settings ####
