# cspell:ignore cmctl gitui krew kubebench kubectx direnv dotenv looztra kompiro kforsthoevel sarg kubeseal stefansedich nlamirault zufardhiyaulhaq sudermanjr openbao kubens
# NOTE: The #### section #### headers below must not be altered or moved as they are used as markers for the install script.

#### Begin Environment
[env]
MISE_PYTHON_COMPILE = false
#### End Environment

[tools]
#### Begin Python
#version#
python = '3.13'
#### End Python

#### Begin HashiCorp Tools
#version#
opentofu = 'latest'
#version#
openbao = 'latest'
#version#
packer = 'latest'
#### End HashiCorp Tools

#### Begin Kubernetes
#version#
kubectl = 'latest'
kubectx = 'latest'
kubens = 'latest'
k9s = 'latest'
helm = 'latest'
kubebench = 'latest'
#### End Kubernetes

#### Begin Kubernetes Utilities
krew = 'latest'
dive = 'latest'
popeye = 'latest'
trivy = 'latest'
cmctl = 'latest'
k3d = 'latest'
#### End Kubernetes Utilities

#### Begin Go Development
#version#
golang = 'latest'
golangci-lint = 'latest'
goreleaser = 'latest'
#### End Go Development

#### Begin .NET Development
#version#
dotnet = 'latest'
#### End .NET Development

#### Begin Node Development
#version#
node = '22.0'
pnpm = 'latest'
yarn = 'latest'
deno = 'latest'
bun = 'latest'
#### End Node Development

#### Begin PowerShell
#version#
powershell = 'latest'
#### End PowerShell

#### Begin Miscellaneous Tools
gitui = 'latest'
cosign = 'latest'
tealdeer = 'latest'
micro = 'latest'
shellcheck = 'latest'
#### End Miscellaneous Tools

# See: https://mise.jdx.dev/dev-tools/aliases.html for specs on the alias section.
[alias]
kubebench = 'asdf:sarg3nt/asdf-kube-bench'
tealdeer = 'asdf:sarg3nt/asdf-tealdeer'
micro = 'asdf:sarg3nt/asdf-micro'

[settings]
experimental = true
http_timeout = '90s'
yes = true
