# Test .mise.toml without JavaScript/Node.js Development section

#### Begin Environment ####
[env]
MISE_PYTHON_COMPILE = false
#### End Environment ####

[tools]
#### Begin HashiCorp Tools ####
opentofu = "latest"
openbao = "latest"
packer = "latest"
#### End HashiCorp Tools ####

#### Begin Kubernetes/Helm ####
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
k9s = "latest"
helm = "latest"
kubebench = "latest"
#### End Kubernetes/Helm ####

#### Begin Go Development ####
golang = 'latest'
golangci-lint = 'latest'
goreleaser = 'latest'
#### End Go Development ####

#### Begin .NET Development ####
dotnet = "latest"
#### End .NET Development ####

# NO JavaScript/Node.js Development section here

#### Begin Miscellaneous Tools ####
gitui = "latest"
tealdeer = "latest"
micro = "latest"
powershell = "latest"
cosign = "latest"
#### End Miscellaneous Tools ####

#### Begin Aliases ####
[alias]
kubebench = 'asdf:sarg3nt/asdf-kube-bench'
tealdeer = 'asdf:sarg3nt/asdf-tealdeer'
micro = 'asdf:sarg3nt/asdf-micro'
#### End Aliases ####

#### Begin Settings ####
[settings]
experimental = true
http_timeout = "90s"
yes = true
#### End Settings ####
