# https://k9scli.io/topics/config/
# default cluster, default context
# This is primarily here to enable nodeShell as that cannot be done in the root config.
k9s:
  # The name of the context parent cluster
  cluster: default
  readOnly: false
  # WARNING: if the namespace section is commented out :q will stop working
  namespace:
    # Active namespace
    active: kube-system
    # Disable k9s favorites ns updates.
    lockFavorites: false
    # Favorite namespaces.
    favorites:
    - all
    - kube-system
  # Active view
  view:
    active: nodes
  # Feature gates toggle k9s features
  featureGates:
    # Enable/Disable nodeShell
    nodeShell: true